### ISSUE TITLE
broken link in contrib/README

### ISSUE THREAD

**Issue by hildred** [openssh/openssh-portable#26]
connect.c is no longer at http://www.taiyo.co.jp/~gotoh/ssh/connect.html. It is not at archive.org I may have found a copy at https://github.com/Shumen/ssh-proxy/blob/master/connect.c but I don't know how current it is.

There also is this bug https://trac.torproject.org/projects/tor/ticket/99

**Comment by djmdjm** [comment]
Fixed in openssh-7.1 - thanks!
